mode: pool
listener:
    address: 0.0.0.0
    port: 2323
    username: proxy
    password: proxy123
multi_port:
    address: ""
    base_port: 0
    username: ""
    password: ""
pool:
    mode: latency_first
    failure_threshold: 3
    blacklist_duration: 24h0m0s
management:
    enabled: true
    listen: 0.0.0.0:9090
    probe_target: www.google.com:80
    password: ""
subscription_refresh:
    enabled: true
    interval: 1h0m0s
    timeout: 30s
    health_check_timeout: 0s
    drain_timeout: 0s
    min_available_nodes: 0
nodes:
    - name: 假节点(仅用于启动)
      uri: vless://00000000-0000-0000-0000-000000000000@127.0.0.1:12345?type=tcp&security=none#FakeNode
      port: 28000
nodes_file: ""
subscriptions:
    - https://gates.djjc.cfd/api/v1/client/subscribe?token=2f186dd498d0d33819ddaa7b6fe6c6b4&flag=meta
subscription_configs: []
external_ip: ""
log_level: info
skip_cert_verify: false
latency_groups:
    low_threshold: 100
    medium_threshold: 300
auto_speedtest:
    enabled: true
    interval: 1m
api_auth:
    enabled: false
    key: ""
