mode: pool
listener:
    address: 0.0.0.0
    port: 2323
    username: proxy
    password: proxy123
multi_port:
    address: ""
    base_port: 0
    username: ""
    password: ""
pool:
    mode: latency_first
    failure_threshold: 3
    blacklist_duration: 24h0m0s
management:
    enabled: true
    listen: 0.0.0.0:9090
    probe_target: www.google.com:80
    password: ""
subscription_refresh:
    enabled: true
    interval: 1h0m0s
    timeout: 30s
    health_check_timeout: 0s
    drain_timeout: 0s
    min_available_nodes: 0
nodes:
    - name: 启动测试节点(假)
      uri: vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIuWQr+WKqOa1i+ivlemKgueCuSIsDQogICJhZGQiOiAiMTI3LjAuMC4xIiwNCiAgInBvcnQiOiAxMjM0LA0KICAiaWQiOiAiYWFhYWFhYWEtYWFhYS1hYWFhLWFhYWEtYWFhYWFhYWFhYWFhIiwNCiAgImFpZCI6IDAsDQogICJzY3kiOi autoIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIvIiwNCiAgInRscyI6ICIiDQp9
      port: 28000
nodes_file: ""
subscriptions:
    - https://webget.yfjc.xyz/api/v1/client/subscribe?token=761b2321a376a8f0c0a89a35ce403293&flag=meta
subscription_configs: []
external_ip: ""
log_level: info
skip_cert_verify: false
latency_groups:
    low_threshold: 100
    medium_threshold: 300
auto_speedtest:
    enabled: true
    interval: 1m
api_auth:
    enabled: false
    key: ""
